### ISSUE TITLE
Thread-24" BUG! exception in phase..

### ISSUE THREAD

**Issue by Jonny023** [pditommaso/groovy_2.3_bug#1]
Hello, may I have any solutions? I also encountered this error now, it seems that the error caused by multiple inheritance or incorrect generics, the server is running, the modified project compiles, there will be Exception in thread "Thread-24" BUG! exception in phase... Type is null. Most probably you let a transform reuse existing ClassNodes with generics information, that is now used in a wrong context.

**Comment by pditommaso** [comment]
it may be related to this issue https://issues.apache.org/jira/browse/GROOVY-9209

**Comment by Jonny023** [comment]
I don't know if it is a problem with the tombstone plugin, because our project also uses this plugin, I have seen this link also encountered this problem. [link](http://qaru.site/questions/17257753/build-error-bug-exception-in-phase-instruction-selection-in-source-set)

**Comment by Jonny023** [comment]
> I tested it, which is related to the Groovy class generics, such as:

```groovy
class C<T> {

}

class A extends C {
    
}
```

> If you do not specify a type, the project will compile and report an error.After testing, if you specify a generic type as a specific type, you will not report an error. The correct wording should be

```groovy
class C<T> {

}

class A extends C<A> {
    
}
```

**Comment by pditommaso** [comment]
I would suggest reporting this in the groovy dev mailing or issue tracking. I'm not affiliated with the dev team.

**Comment by Jonny023** [comment]
ok
